import type { CalendarType } from '../calendar';

export const April2026: CalendarType = [
{
	date: '2026-04-01',
	week: 1,
	season: 'pascha',
	holidays: ['WIELKA ŚRODA'],
	notes: [
		'[HTML]Marii Egipcjanki[HTML] mn.',
		'[HTML]Melitona z Sardes[HTML] bp.',
	],
	passages: [
		'Iz 50, 4-9a',
		'Ps 69',
		'Mt 26, 14-25',
	],
	links: [
		{ name: 'jutrznia', slug: 'wielka-sroda-jutrznia' },
		{ name: 'nieszpory', slug: 'wielka-sroda-nieszpory' },
		{ name: 'kompleta', slug: 'wielka-sroda-kompleta' },
	],
},
{
	date: '2026-04-02',
	week: 1,
	season: 'pascha',
	holidays: ['WIELKI CZWARTEK'],
	notes: [
		'[HTML]Franciszka z Paoli[HTML] mn.',
	],
	passages: [
		'Wj 12, 1-8, 11-14',
		'Ps 116',
		'1 Kor 11, 23-26',
		'J 13, 1-15',
	],
	links: [
		{ name: 'jutrznia', slug: 'wielki-czwartek-jutrznia' },
		{ name: 'wigilia Wielkiego Piątku', slug: 'wielki-piatek-wigilia' },
		{ name: 'godzina czytań', slug: 'wielki-piatek-godzina-czytan' },
		{ name: 'kompleta', slug: 'wielki-piatek-kompleta-1' },
	],
},
{
	date: '2026-04-03',
	week: 1,
	season: 'pascha',
	holidays: ['WIELKI PIĄTEK'],
	passages: [
		'Iz 52, 13-53, 12',
		'Ps 31',
		'Hbr 4, 14-16; 5, 7-9',
		'J 18, 1-19, 42',
	],
	links: [
		{ name: 'jutrznia', slug: 'wielki-piatek-jutrznia' },
		{ name: 'godzina czytań', slug: 'wielki-piatek-godzina-czytan' },
		{ name: 'nieszpory', slug: 'wielki-piatek-nieszpory' },
		{ name: 'kompleta', slug: 'wielki-piatek-kompleta-2' },
	],
},
{
	date: '2026-04-04',
	week: 1,
	season: 'pascha',
	holidays: ['WIELKA SOBOTA'],
	notes: [
		'[HTML]Izydora z Sewilli[HTML] bp.',
	],
	passages: [
		'Rdz 1, 1-2, 2',
		'Ps 104',
		'Rdz 22, 1-18',
		'Ps 16',
		'Wj 14, 15-15, 1',
		'Wj 15',
		'Iz 54, 5-14',
		'Ps 30',
		'Iz 55, 1-11',
		'Iz 12',
		'Ba 3, 9-15, 32-4, 4',
		'Ps 19',
		'Ez 36, 16-17a, 18-28',
		'Ps 42, 43',
		'Rz 6, 3-11',
		'Mt 28, 1-10',
	],
	links: [
		{ name: 'jutrznia', slug: 'wielka-sobota-jutrznia' },
		{ name: 'godzina czytań', slug: 'wielka-sobota-godzina-czytan' },
		{ name: 'w ciągu dnia', slug: 'wielka-sobota-w-ciagu-dnia' },
	],
},
{
	date: '2026-04-05',
	week: 2,
	season: 'easter',
	holidays: ['PASCHA'],
	passages: [
		'Dz 10, 34a, 37-43',
		'Ps 118',
		['Kol 3, 1-4', '1 Kor 5, 6b-8'],
		'J 20, 1-9',
	],
	links: [
		{ name: 'nieszpory Wielkiej Soboty', slug: 'wielka-sobota-nieszpory' },
		{ name: 'godzina czytań', slug: 'wielka-sobota-godzina-czytan' },
		{ name: 'kompleta', slug: 'wielka-sobota-kompleta' },
		{ name: 'jutrznia', slug: 'niedziela-zmartwychwstania-jutrznia' },
		{ name: 'nieszpory', slug: 'niedziela-zmartwychwstania-nieszpory' },
		{ name: 'kompleta', slug: 'niedziela-zmartwychwstania-kompleta' },
	],
},
{
	date: '2026-04-06',
	week: 2,
	season: 'easter',
	holidays: ['PONIEDZIAŁEK PASCHALNY'],
	notes: [
		'[HTML]Jacquesa Fescha[HTML] w.',
	],
	passages: [
		'Dz 2, 14, 22-33',
		'Ps 16',
		'Mt 28, 8-15',
	],
	links: [
		{ name: 'jutrznia', slug: 'oktawa-paschalna-jutrznia' },
		{ name: 'nieszpory', slug: 'oktawa-paschalna-nieszpory' },
		{ name: 'kompleta', slug: 'oktawa-paschalna-poniedzialek-kompleta' },
	],
	vespers: {
		antiphon: 'Jezus stanął przed niewiastami i powiedział: "Witajcie"! * One zaś zbliżyły się do Niego, / objęły Go za nogi i oddały Mu pokłon, / alleluja.',
		sigla: 'Hbr 8, 1b-5a',
		passage: 'Takiego mamy arcykapłana, który zasiadł po prawicy tronu Majestatu w niebiosach, jako sługa świątyni i prawdziwego przybytku zbudowanego przez Pana, a nie przez człowieka. Każdy bowiem arcykapłan ustanawiany jest do składania darów i ofiar.',
	},
	lauds: {
		antiphon: 'Idźcie z pośpiechem * i powiedzcie uczniom, / że Pan zmartwychwstał, / alleluja.',
		sigla: 'Rz 10, 8b-10',
		passage: 'Ustanowiłem Cię przymierzem dla ludu, aby odnowić kraj, aby rozdzielić spustoszone dziedzictwa, aby rzec więźniom: „Wyjdźcie na wolność!”, a marniejącym w ciemnościach: „Ukażcie się!”',
	},
},
{
	date: '2026-04-07',
	week: 2,
	season: 'easter',
	holidays: ['WTOREK PASCHALNY'],
	passages: [
		'Dz 2, 36-41',
		'Ps 33',
		'J 20, 11-18',
	],
	links: [
		{ name: 'jutrznia', slug: 'oktawa-paschalna-jutrznia' },
		{ name: 'nieszpory', slug: 'oktawa-paschalna-nieszpory' },
		{ name: 'kompleta', slug: 'oktawa-paschalna-wtorek-kompleta' },
	],
	vespers: {
		antiphon: 'Kiedy płakałam przy grobie, * ujrzałam mego Pana, / alleluja.',
		sigla: '1 P 2, 4-5',
		passage: 'Zbliżając się do Pana, który jest żywym kamieniem, odrzuconym wprawdzie przez ludzi, ale u Boga wybranym i drogocennym, wy również niby żywe kamienie jesteście budowani jako duchowa świątynia, by stanowić święte kapłaństwo, dla składania duchowych ofiar, przyjemnych Bogu przez Jezusa Chrystusa.',
	},
	lauds: {
		antiphon: 'Jezus powiedział: "Mario!" * Ona zaś obróciwszy się do Niego, rzekła: "Nauczycielu!" / A On powiedział: "Nie zatrzymuj Mnie, / jeszcze bowiem nie wstąpiłem do Ojca", / alleluja.',
		sigla: 'Dz 13, 30-33',
		passage: 'Bóg wskrzesił Jezusa z martwych, a On ukazywał się Przez wiele dni tym, którzy z Nim razem poszli z Galilei do Jerozolimy, a teraz dają świadectwo o Nim przed ludem. My właśnie głosimy wam Dobrą Nowinę, co do obietnicy danej ojcom:że Bóg spełnił ją wobec nas jako dzieci, wskrzesiwszy Jezusa. Tak też jest napisanew psalmie drugim: Ty jesteś moim Synem, jam Ciebie dziś zrodził.',
	},
},
{
	date: '2026-04-08',
	week: 2,
	season: 'easter',
	holidays: ['ŚRODA PASCHALNA'],
	passages: [
		'Dz 3, 1-10',
		'Ps 105',
		'Łk 24, 13-35',
	],
	links: [
		{ name: 'jutrznia', slug: 'oktawa-paschalna-jutrznia' },
		{ name: 'nieszpory', slug: 'oktawa-paschalna-nieszpory' },
		{ name: 'kompleta', slug: 'oktawa-paschalna-sroda-kompleta' },
	],
	vespers: {
		antiphon: 'Jezus wszedł z uczniami do domu, * i usiadł z nimi przy stole, / wziął chleb, błogosławił go i łamał, / i podał owym dwom uczniom, / alleluja.',
		sigla: 'Hbr 7, 24-27',
		passage: 'Jezus, ponieważ trwa na wieki, ma kapłaństwo nieprzemijające. Przeto i zbawić na wieki może całkowicie tych, którzy przez Niego zbliżają się do Boga, bo zawsze żyje, aby się wstawiać za nami. Takiego bowiem potrzeba nam było Arcykapłana: świętego, niewinnego, nieskalanego, oddzielonego od grzeszników, wywyższonego ponad niebiosa, takiego, który nie jest obowiązany, jak inni arcykapłani, do składania codziennej ofiary najpierw za swoje grzechy, a potem za grzechy ludu. To bowiem uczynił raz na zawsze ofiarując samego siebie.',
	},
	lauds: {
		antiphon: 'Jezus wyjaśniał uczniom, * zaczynając od Mojżesza poprzez wszystkich proroków, / wszystko, co w Piśmie odnosiło się do Niego, / alleluja.',
		sigla: 'Rz 6, 8-11',
		passage: 'Jeżeli umarliśmy razem z Chrystusem, wierzymy, że z Nim również żyć będziemy, wiedząc, że Chrystus powstawszy z martwych już więcej nie umiera, śmierć nad Nim nie ma już władzy. Bo to, że umarł, umarł dla grzechu tylko raz, a że żyje, żyje dla Boga. Tak i wy rozumiejcie, że umarliście dla grzechu, żyjecie zaś dla Boga w Chrystusie Jezusie.',
	},
},
{
	date: '2026-04-09',
	week: 2,
	season: 'easter',
	holidays: ['CZWARTEK PASCHALNY'],
	notes: [
		'[HTML]Dietricha Bonhoeffera[HTML] m.',
		'[HTML]Achacego z Amidy[HTML] bp.',
	],
	passages: [
		'Dz 3, 11-26',
		'Ps 8',
		'Łk 24, 35-48',
	],
	links: [
		{ name: 'jutrznia', slug: 'oktawa-paschalna-jutrznia' },
		{ name: 'nieszpory', slug: 'oktawa-paschalna-nieszpory' },
		{ name: 'kompleta', slug: 'oktawa-paschalna-czwartek-kompleta' },
	],
	vespers: {
		antiphon: 'Popatrzcie na ręce moje i na nogi, * to Ja przecież jestem, / alleluja.',
		sigla: '1 P 3, 18. 22',
		passage: 'Chrystus raz umarł za grzechy, sprawiedliwy za niesprawiedliwych, aby nas do Boga przyprowadzić; zabity wprawdzie na ciele, ale powołany do życia Duchem. On jest po prawicy Bożej, gdyż poszedł do nieba, gdzie poddani Mu zostali aniołowie i Moce, i Potęgi!',
	},
	lauds: {
		antiphon: 'Stanął Jezus pośród swoich uczniów * i rzekł do nich: Pokój wam. / alleluja.',
		sigla: 'Rz 8, 10-11',
		passage: 'Jeżeli Chrystus w was mieszka, ciało wprawdzie podlega śmierci ze względu na skutki grzechu, duch jednak posiada życie na skutek usprawiedliwienia. A jeżeli mieszka w nas Duch Tego, który Jezusa wskrzesił z martwych, to Ten, co wskrzesił Chrystusa Jezusa z martwych, przywróci do życia wasze śmiertelne ciała mocą mieszkającego w was swego Ducha.',
	},
},
{
	date: '2026-04-10',
	week: 2,
	season: 'easter',
	holidays: ['PIĄTEK PASCHALNY'],
	passages: [
		'Dz 4, 1-12',
		'Ps 118',
		'J 21, 1-14',
	],
	links: [
		{ name: 'jutrznia', slug: 'oktawa-paschalna-jutrznia' },
		{ name: 'nieszpory', slug: 'oktawa-paschalna-nieszpory' },
		{ name: 'kompleta', slug: 'oktawa-paschalna-piatek-kompleta' },
	],
	vespers: {
		antiphon: 'Powiedział uczeń, którego Jezus miłował: * To jest nasz Pan, / alleluja.',
		sigla: 'Hbr 5, 8-10',
		passage: 'Chrystus, chociaż był Synem, nauczył się posłuszeństwa przez to, co wycierpiał. A gdy wszystko wykonał, stał się sprawcą zbawienia wiecznego dla wszystkich, którzy Go słuchają, nazwany przez Boga Kapłanem na wzór Melchizedeka.',
	},
	lauds: {
		antiphon: 'Już trzeci raz Jezus ukazał się uczniom * od chwili swego zmartwychwstania, / alleluja.',
		sigla: 'Dz 5, 30-32',
		passage: 'Bóg naszych ojców wskrzesił Jezusa, którego straciliście, przybiwszy do krzyża. Bóg wywyższył Go na prawicę swoją jako Władcę i Zbawiciela, aby dać Izraelowi nawrócenie i odpuszczenie grzechów. Dajemy temu świadectwo my właśnie oraz Duch Święty, którego Bóg udzielił tym, którzy są Mu posłuszni.',
	},
},
{
	date: '2026-04-11',
	week: 2,
	season: 'easter',
	holidays: ['SOBOTA PASCHALNA'],
	passages: [
		'Dz 4, 13-21',
		'Ps 118',
		'Mk 16, 9-15',
	],
	links: [
		{ name: 'jutrznia', slug: 'oktawa-paschalna-jutrznia' },
		{ name: 'nieszpory', slug: 'oktawa-paschalna-nieszpory' },
		{ name: 'kompleta', slug: 'oktawa-paschalna-sobota-kompleta' },
	],
	vespers: {
		antiphon: 'Po ośmiu dniach, mimo drzwi zamkniętych, * Jezus stanął pośród uczniów / i rzekł do nich: Pokój wam, alleluja.',
		sigla: '1 P 2, 9-10',
		passage: 'Wy jesteście wybranym plemieniem, królewskim kapłaństwem, świętym narodem, ludem Bogu na własność przeznaczonym, abyście ogłaszali dzieła potęgi Tego, który was wezwał z ciemności do przedziwnego swojego światła, wy, którzyście byli nie-ludem, teraz zaś jesteście ludem Bożym, którzyście nie dostąpili miłosierdzia, teraz zaś jako ci, którzy miłosierdzia doznali.',
	},
	lauds: {
		antiphon: 'Po swoim zmartwychwstaniu * wczesnym rankiem w pierwszy dzień tygodnia, / Jezus ukazał się najpierw Marii Magdalenie, / z której wyrzucił siedem złych duchów, / alleluja.',
		sigla: 'Rz 14, 7-9',
		passage: 'Nikt z nas nie żyje dla siebie i nikt nie umiera dla siebie: jeżeli bowiem żyjemy, żyjemy dla Pana; jeżeli zaś umieramy, umieramy dla Pana. I w życiu więc, i w śmierci należymy do Pana. Po to bowiem Chrystus umarł i powrócił do życia, by zapanować tak nad umarłymi, jak i nad żywymi.',
	},
},
{
	date: '2026-04-12',
	week: 1,
	season: 'easter',
	holidays: ['2. NIEDZIELA PASCHALNA'],
	passages: [
		'Dz 2, 42-47',
		'Ps 118',
		'1 P 1, 3-9',
		'J 20, 19-31',
	],
	links: [
		{ name: 'jutrznia', slug: 'oktawa-paschalna-jutrznia' },
		{ name: 'nieszpory', slug: 'oktawa-paschalna-nieszpory' },
		{ name: 'kompleta', slug: 'oktawa-paschalna-niedziela-kompleta' },
		{ name: 'liturgia słowa', slug: 'czytania/niedziela-w-oktawie-zmartwychwstania-panskiego-rok-a' },
	],
	vespers: {
		antiphon: 'Uwierzyłeś, bo Mnie ujrzałeś, Tomaszu, * błogosławieni, którzy nie widzieli, a uwierzyli, / alleluja.',
		sigla: 'Hbr 10, 12-14',
		passage: 'Chrystus złożywszy raz na zawsze jedną ofiarę za grzechy, zasiadł po prawicy Boga, oczekując tylko, aż nieprzyjaciele Jego staną się podnóżkiem nóg Jego. Jedną bowiem ofiarą udoskonalił na wieki tych, którzy są uświęceni.',
	},
	lauds: {
		antiphon: 'Wyciągnij rękę i dotknij miejsca gwoździ, * i nie bądź niedowiarkiem, lecz wierzącym, / alleluja.',
		sigla: 'Dz 10, 40-43',
		passage: 'Bóg wskrzesił Jezusa trzeciego dnia i pozwolił Mu ukazać się nie całemu ludowi, ale nam, wybranym uprzednio przez Boga na świadków, którzyśmy z Nim jedli i pili po Jego zmartwychwstaniu. On nam rozkazał ogłosić ludowi i dać świadectwo, że Bóg ustanowił Go sędzią żywych i umarłych. Wszyscy prorocy świadczą o tym, że każdy, kto w Niego wierzy, w Jego imię otrzymuje odpuszczenie grzechów.',
	},
},
{
	date: '2026-04-13',
	week: 2,
	season: 'easter',
	passages: [
		'Dz 4, 23-31',
		'Ps 2',
		'J 3, 1-8',
	],
},
{
	date: '2026-04-14',
	week: 2,
	season: 'easter',
	passages: [
		'Dz 4, 32-37',
		'Ps 93',
		'J 3, 7b-15',
	],
},
{
	date: '2026-04-15',
	week: 2,
	season: 'easter',
	passages: [
		'Dz 5, 17-26',
		'Ps 34',
		'J 3, 16-21',
	],
},
{
	date: '2026-04-16',
	week: 2,
	season: 'easter',
	passages: [
		'Dz 5, 27-33',
		'Ps 34',
		'J 3, 31-36',
	],
},
{
	date: '2026-04-17',
	week: 2,
	season: 'easter',
	passages: [
		'Dz 5, 34-42',
		'Ps 27',
		'J 6, 1-15',
	],
},
{
	date: '2026-04-18',
	week: 2,
	season: 'easter',
	passages: [
		'Dz 6, 1-7',
		'Ps 33',
		'J 6, 16-21',
	],
},
{
	date: '2026-04-19',
	week: 1,
	season: 'easter',
	holidays: ['3. NIEDZIELA PASCHALNA'],
	passages: [
		'Dz 2, 14, 22-32',
		'Ps 16',
		'1 P 1, 17-21',
		'Łk 24, 13-35',
	],
},
{
	date: '2026-04-20',
	week: 1,
	season: 'easter',
	passages: [
		'Dz 6, 8-15',
		'Ps 119',
		'J 6, 22-29',
	],
},
{
	date: '2026-04-21',
	week: 1,
	season: 'easter',
	passages: [
		'Dz 7, 51-8, 1a',
		'Ps 31',
		'J 6, 30-35',
	],
},
{
	date: '2026-04-22',
	week: 1,
	season: 'easter',
	passages: [
		'Dz 8, 1b-8',
		'Ps 66',
		'J 6, 35-40',
	],
},
{
	date: '2026-04-23',
	week: 1,
	season: 'easter',
	holidays: ['WOJCIECHA'],
	passages: [
		'Dz 1, 3-8',
		'Ps 126',
		'Flp 1, 20c-30',
		'J 12, 24-26',
	],
},
{
	date: '2026-04-24',
	week: 1,
	season: 'easter',
	notes: [
		'[HTML]Zenona "Zeno" Żebrowskiego[HTML] zak. misj.',
	],
	passages: [
		'Dz 9, 1-20',
		'Ps 117',
		'J 6, 52-59',
	],
},
{
	date: '2026-04-25',
	week: 1,
	season: 'easter',
	holidays: ['MARKA EWANGELISTY'],
	passages: [
		'1 P 5, 5b-14',
		'Ps 89',
		'Mk 16, 15-20',
	],
},
{
	date: '2026-04-26',
	week: 2,
	season: 'easter',
	holidays: ['4. NIEDZIELA PASCHALNA'],
	passages: [
		'Dz 2, 14a, 36-41',
		'Ps 23',
		'1 P 2, 20b-25',
		'J 10, 1-10',
	],
},
{
	date: '2026-04-27',
	week: 2,
	season: 'easter',
	passages: [
		'Dz 11, 1-18',
		'Ps 42',
		'J 10, 11-18',
	],
},
{
	date: '2026-04-28',
	week: 2,
	season: 'easter',
	notes: [
		'[HTML]Joanny Beretty Molli[HTML] w.',
	],
	passages: [
		'Dz 11, 19-26',
		'Ps 87',
		'J 10, 22-30',
	],
},
{
	date: '2026-04-29',
	week: 2,
	season: 'easter',
	notes: [
		'[HTML]Katarzyny ze Sieny[HTML] zak.',
	],
	passages: [
		'Dz 12, 24-13, 5a',
		'Ps 67',
		'J 12, 44-50',
	],
},
{
	date: '2026-04-30',
	week: 2,
	season: 'easter',
	notes: [
		'[HTML]Jakuba z Paradyża[HTML] mn.',
	],
	passages: [
		'Dz 13, 13-25',
		'Ps 89',
		'J 13, 16-20',
	],
},
];