import type { CalendarType } from './calendar';

export const October2021: CalendarType = [
  {
    date: '2021-10-01',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML]Teresy z Lisieux[HTML] zak. i teo.'],
    passages: ['Ba 1,15-22', 'Ps 79,1-2.3-4.5.8.9', 'Łk 10,13-16'],
  },
  {
    date: '2021-10-02',
    week: 1,
    season: 'ordinary',
    passages: ['Ba 4,5-12.27-29', 'Ps 69,33-37', 'Łk 10,17-24'],
  },
  {
    date: '2021-10-03',
    week: 2,
    holiday: '19. NIEDZIELA PO PIĘĆDZIESIĄTNICY',
    season: 'ordinary',
    passages: ['', '', ''],
  },
  {
    date: '2021-10-04',
    week: 2,
    season: 'ordinary',
    notes: ['[HTML][HTML]'],
    passages: ['', '', ''],
  },
  {
    date: '2021-10-05',
    week: 2,
    season: 'ordinary',
    notes: ['[HTML][HTML]'],
    passages: ['', '', ''],
  },
  {
    date: '2021-10-06',
    week: 2,
    season: 'ordinary',
    notes: ['[HTML][HTML]'],
    passages: ['', '', ''],
  },
  {
    date: '2021-10-07',
    week: 2,
    season: 'ordinary',
    notes: ['[HTML][HTML]'],
    passages: ['', '', ''],
  },
  { date: '2021-10-08', week: 2, season: 'ordinary', passages: ['', '', ''] },
  {
    date: '2021-10-09',
    week: 2,
    season: 'ordinary',
    holiday: '',
    passages: ['', '', ''],
  },
  {
    date: '2021-10-10',
    week: 1,
    season: 'ordinary',
    holiday: '',
    passages: ['', '', ''],
  },
  {
    date: '2021-10-11',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML][HTML]'],
    passages: ['', '', ''],
  },
  {
    date: '2021-10-12',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML][HTML]'],
    passages: ['', '', ''],
  },
  { date: '2021-10-13', week: 1, season: 'ordinary', passages: ['', '', ''] },
  { date: '2021-10-14', week: 1, season: 'ordinary', passages: ['', '', ''] },
  {
    date: '2021-10-15',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML][HTML]'],
    passages: ['', '', ''],
  },
  { date: '2021-10-16', week: 1, season: 'ordinary', passages: ['', '', ''] },
  {
    date: '2021-10-17',
    week: 2,
    season: 'ordinary',
    notes: ['[HTML][HTML]'],
    holiday: '',
    passages: ['', '', ''],
  },
  {
    date: '2021-10-18',
    week: 2,
    season: 'ordinary',
    holiday: '',
    passages: ['', '', ''],
  },
  { date: '2021-10-19', week: 2, season: 'ordinary', passages: ['', '', ''] },
  { date: '2021-10-20', week: 2, season: 'ordinary', passages: ['', '', ''] },
  { date: '2021-10-21', week: 2, season: 'ordinary', passages: ['', '', ''] },
  { date: '2021-10-22', week: 2, season: 'ordinary', passages: ['', '', ''] },
  {
    date: '2021-10-23',
    week: 2,
    season: 'ordinary',
    holiday: '',
    passages: ['', '', ''],
  },
  {
    date: '2021-10-24',
    week: 1,
    season: 'ordinary',
    holiday: '',
    passages: ['', '', ''],
  },
  { date: '2021-10-25', week: 1, season: 'ordinary', passages: ['', '', ''] },
  { date: '2021-10-26', week: 1, season: 'ordinary', passages: ['', '', ''] },
  {
    date: '2021-10-27',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML][HTML]'],
    passages: ['', '', ''],
  },
  {
    date: '2021-10-28',
    week: 1,
    season: 'ordinary',
    holiday: '',
    passages: ['', '', ''],
  },
  {
    date: '2021-10-29',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML][HTML]'],
    passages: ['', '', ''],
  },
  { date: '2021-10-30', week: 1, season: 'ordinary', passages: ['', '', ''] },
  {
    date: '2021-10-31',
    week: 2,
    season: 'ordinary',
    holiday: '',
    passages: ['', '', ''],
  },
];
