import type { CalendarType } from './calendar';

export const March2022: CalendarType = [
  {
    date: '2022-03-01',
    week: 2,
    season: 'christmas',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-02',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-03',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-04',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-05',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-06',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-07',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-08',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-09',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-10',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-11',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-12',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-13',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-14',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-15',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-16',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-17',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-18',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-19',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-20',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-21',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-22',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-23',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-24',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-25',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-26',
    week: 1,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-27',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-28',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-29',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-30',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-03-31',
    week: 2,
    season: 'lent',
    passages: [''],
    holidays: [''],
    notes: ['[HTML][HTML] '],
  },
];
