import type { CalendarType } from './calendar';

export const July2022: CalendarType = [
  {
    date: '2022-07-01',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-02',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-03',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-04',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-05',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-06',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-07',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-08',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-09',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-10',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-11',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-12',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-13',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-14',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-15',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-16',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-17',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-18',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-19',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-20',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-21',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-22',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-23',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-24',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-25',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-26',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-27',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-28',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-29',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-07-30',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
];
