import type { CalendarType } from './calendar';

export const June2022: CalendarType = [
  {
    date: '2022-06-01',
    week: 1,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-02',
    week: 1,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-03',
    week: 1,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-04',
    week: 1,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-05',
    week: 1,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-06',
    week: 1,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-07',
    week: 1,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-08',
    week: 2,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-09',
    week: 2,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-10',
    week: 2,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-11',
    week: 2,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-12',
    week: 2,
    season: 'pentecost',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-13',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-14',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-15',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-16',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-17',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-18',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-19',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-20',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-21',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-22',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-23',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-24',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-25',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-26',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-27',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-28',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-29',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-06-30',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
];
