import type { CalendarType } from './calendar';

export const September2022: CalendarType = [
  {
    date: '2022-09-01',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-02',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-03',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-04',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-05',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-06',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-07',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-08',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-09',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-10',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-11',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-12',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-13',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-14',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-15',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-16',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-17',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-18',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-19',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-20',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-21',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-22',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-23',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-24',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-25',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-26',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-27',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-28',
    week: 2,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-29',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
  {
    date: '2022-09-30',
    week: 1,
    season: 'ordinary',
    holidays: [],
    passages: [],
    notes: [],
  },
];
