import type { CalendarType } from './calendar';

export const November2022: CalendarType = [
  {
    date: '2022-11-01',
    week: 2,
    season: 'ordinary',
    passages: [],
    holidays: ['WSZYSTKICH ŚWIĘTYCH'],
    links: [
      { name: 'jutrznia', slug: 'jutrznia-o-swietych' },
      { name: 'nieszpory', slug: 'nieszpory-o-swietych' },
    ],
    linksTitle: '[HTML]Modlitwy na dziś:[HTML]',
  },
  {
    date: '2022-11-02',
    week: 2,
    season: 'ordinary',
    passages: [],
    notes: ['[HTML]Wszystkich wiernych zmarłych[HTML]'],
  },
  {
    date: '2022-11-03',
    week: 2,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-11-04',
    week: 2,
    season: 'ordinary',
    passages: [],
    notes: ['[HTML]Henryka Knapika[HTML] teo.'],
  },
  {
    date: '2022-11-05',
    week: 2,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-11-06',
    week: 1,
    season: 'ordinary',
    holidays: ['22. NIEDZIELA PO PIĘĆDZIESIĄTNICY'],
    passages: [],
  },
  {
    date: '2022-11-07',
    week: 1,
    season: 'ordinary',
    passages: [],
    holidays: ['WILIBRORDA'],
    notes: ['Dzień modlitwy za wspólnoty starokatolickie na świecie'],
    links: [
      { name: 'biogram', slug: 'wilibrord-biogram' },
      { name: 'jutrznia', slug: 'wilibrord-jutrznia' },
      { name: 'nieszpory', slug: 'wilibrord-nieszpory' },
    ],
    linksTitle: '[HTML]Wilibrorda bp. Utrechtu[HTML]',
  },
  {
    date: '2022-11-08',
    week: 1,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-11-09',
    week: 1,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-11-10',
    week: 1,
    season: 'ordinary',
    passages: [],
    notes: ['[HTML]Leona[HTML] bp. teo.'],
  },
  {
    date: '2022-11-11',
    week: 1,
    season: 'ordinary',
    passages: [],
    notes: ['[HTML]Marcina[HTML] bp. Tours'],
  },
  {
    date: '2022-11-12',
    week: 1,
    season: 'ordinary',
    passages: [],
    notes: ['[HTML]Pierwszych pięciu męczenników polskich[HTML] mn. i misj.'],
  },
  {
    date: '2022-11-13',
    week: 2,
    season: 'ordinary',
    holidays: ['23. NIEDZIELA PO PIĘĆDZIESIĄTNICY'],
    passages: [],
  },
  {
    date: '2022-11-14',
    week: 2,
    season: 'ordinary',
    passages: [],
    notes: ['[HTML]Wszystkich współczesnych męczenników[HTML]'],
  },
  {
    date: '2022-11-15',
    week: 2,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-11-16',
    week: 2,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-11-17',
    week: 2,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-11-18',
    week: 2,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-11-19',
    week: 2,
    season: 'ordinary',
    passages: [],
    notes: [
      '[HTML]Hildy z Whitby[HTML] mn.',
      '[HTML]Mechtyldy z Magdeburga[HTML] mist.',
    ],
  },
  {
    date: '2022-11-20',
    week: 1,
    season: 'ordinary',
    holidays: ['CHRYSTUSA PANTOKRATORA'],
    passages: [],
  },
  {
    date: '2022-11-21',
    week: 1,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-11-22',
    week: 1,
    season: 'ordinary',
    passages: [],
    notes: ['[HTML]Clive’a Staplesa Lewisa[HTML] pisarza i apologety'],
  },
  {
    date: '2022-11-23',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML]Kolumbana[HTML] mn.'],
    passages: [],
  },
  {
    date: '2022-11-24',
    week: 1,
    season: 'ordinary',
    passages: [],
    notes: ['[HTML]Grzegorza Peradze[HTML] prezb. i m.'],
  },
  {
    date: '2022-11-25',
    week: 1,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-11-26',
    week: 1,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-11-27',
    week: 1,
    season: 'ordinary',
    passages: [],
    holidays: ['1. NIEDZIELA ADWENTU'],
    notes: ['[HTML]Grzegorza Palamasa[HTML] bp.'],
  },
  {
    date: '2022-11-28',
    week: 1,
    season: 'advent',
    passages: [],
  },
  {
    date: '2022-11-29',
    week: 1,
    season: 'advent',
    passages: [],
    notes: ['[HTML]Doroty Day[HTML] wyzn.'],
  },
  {
    date: '2022-11-30',
    week: 1,
    season: 'advent',
    passages: [],
    holidays: ['ANDRZEJA APOSTOŁA'],
  },
];
