import type { CalendarType } from './calendar';

export const October2022: CalendarType = [
  {
    date: '2022-10-01',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML]Teresy od Dzieciątka Jezus[HTML] zak. i teo.'],
    passages: [],
  },
  {
    date: '2022-10-02',
    week: 2,
    season: 'ordinary',
    holidays: ['17. NIEDZIELA PO PIĘĆDZIESIĄTNICY'],
    passages: [],
  },
  {
    date: '2022-10-03',
    week: 2,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-04',
    week: 2,
    season: 'ordinary',
    notes: ['[HTML]Franciszka z Asyżu[HTML] dk. i zak.'],
    passages: [],
  },
  {
    date: '2022-10-05',
    week: 2,
    season: 'ordinary',
    notes: ['[HTML]Sergiusza i Bachusa[HTML] m.'],
    passages: [],
  },
  {
    date: '2022-10-06',
    week: 2,
    season: 'ordinary',
    notes: ['[HTML]Brunona z Kolonii[HTML] mn.'],
    passages: [],
  },
  {
    date: '2022-10-07',
    week: 2,
    season: 'ordinary',
    notes: ['[HTML]Chiary Luce Badano[HTML] w.'],
    passages: [],
  },
  {
    date: '2022-10-08',
    week: 2,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-09',
    week: 1,
    season: 'ordinary',
    holidays: ['18. NIEDZIELA PO PIĘĆDZIESIĄTNICY'],
    notes: ['[HTML]Abrahama i Sary[HTML]'],
    passages: [],
  },
  {
    date: '2022-10-10',
    week: 1,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-11',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML]Filipa[HTML] dk.'],
    passages: [],
  },
  {
    date: '2022-10-12',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML]Radzyma Gaudentego[HTML] bp.'],
    passages: [],
  },
  {
    date: '2022-10-13',
    week: 1,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-14',
    week: 1,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-15',
    week: 1,
    season: 'ordinary',
    notes: [
      '[HTML]Teresy z Avila[HTML] mn.',
      '[HTML]Samuela Szereszewskiego [HTML] bp.',
    ],
    passages: [],
  },
  {
    date: '2022-10-16',
    week: 2,
    season: 'ordinary',
    holidays: ['19. NIEDZIELA PO PIĘĆDZIESIĄTNICY'],
    passages: [],
  },
  {
    date: '2022-10-17',
    week: 2,
    season: 'ordinary',
    notes: ['[HTML]Ignacego[HTML] bp. i m.'],
    passages: [],
  },
  {
    date: '2022-10-18',
    week: 2,
    season: 'ordinary',
    holidays: ['ŁUKASZA EWANGELISTY'],
    passages: [],
  },
  {
    date: '2022-10-19',
    week: 2,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-20',
    week: 2,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-21',
    week: 2,
    season: 'ordinary',
    notes: ['DZIEŃ WSPÓLNEGO POSTU'],
    passages: [],
  },
  {
    date: '2022-10-22',
    week: 2,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-23',
    week: 1,
    season: 'ordinary',
    holidays: ['20. NIEDZIELA PO PIĘĆDZIESIĄTNICY'],
    notes: ['[HTML]Jakuba[HTML] ap. bp. m'],
    passages: [],
  },
  {
    date: '2022-10-24',
    week: 1,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-25',
    week: 1,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-26',
    week: 1,
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-27',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML]Jana Czuby[HTML] prezb. misj. i m'],
    passages: [],
  },
  {
    date: '2022-10-28',
    week: 1,
    season: 'ordinary',
    holidays: ['SZYMONA I JUDY APOSTOŁÓW'],
    passages: [],
  },
  {
    date: '2022-10-29',
    week: 1,
    season: 'ordinary',
    notes: ['[HTML]Emmanuelle Madeleine Cinquin[HTML] zak.'],
    passages: [],
  },
  {
    date: '2022-10-30',
    week: 2,
    holidays: ['21. NIEDZIELA PO PIĘĆDZIESIĄTNICY'],
    season: 'ordinary',
    passages: [],
  },
  {
    date: '2022-10-31',
    week: 2,
    season: 'ordinary',
    passages: [],
    links: [
      { name: 'Wigilia dnia Wszystkich Świętych', slug: 'wigilia-o-swietych' },
    ],
  },
];
