import type { CalendarType } from './calendar';

export const February2022: CalendarType = [
  {
    date: '2022-02-01',
    week: 2,
    season: 'christmas',
    passages: ['2 Sm 18, 9-10, 14b, 24-25a, 30-19, 3', 'Ps 86', 'Mk 5, 21-43'],
    notes: ['[HTML]Brygidy z Kildare[HTML] mn.'],
  },
  {
    date: '2022-02-02',
    week: 2,
    season: 'christmas',
    passages: ['Ml 3, 1-4', 'Ps 24', 'Hbr 2, 14-18', 'Łk 2, 22-40'],
    holidays: ['HYPAPANTE'],
  },
  {
    date: '2022-02-03',
    week: 2,
    season: 'christmas',
    passages: ['1 Krl 2, 1-4, 10-12 1', 'Krn 29', 'Flp 2, 1-11', 'Mk 6, 7-13'],
    notes: ['[HTML]Błażeja[HTML] bp. i m.', '[HTML]Oskara[HTML] bp.'],
  },
  {
    date: '2022-02-04',
    week: 2,
    season: 'christmas',
    passages: ['Syr 47, 2-11', 'Ps 18', 'Mk 6, 14-29'],
  },
  {
    date: '2022-02-05',
    week: 2,
    season: 'christmas',
    passages: ['1 Krl 3, 4-13', 'Ps 119', 'Mk 6, 30-34'],
  },
  {
    date: '2022-02-06',
    week: 1,
    season: 'christmas',
    passages: ['Iz 6, 1-2a, 3-8', 'Ps 138', '1 Kor 15, 1-11', 'Łk 5, 1-11'],
    holidays: ['5. NIEDZIELA PO EPIFANII'],
  },
  {
    date: '2022-02-07',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-08',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-09',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-10',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-11',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-12',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-13',
    week: 2,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-14',
    week: 2,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-15',
    week: 2,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-16',
    week: 2,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-17',
    week: 2,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-18',
    week: 2,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-19',
    week: 2,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-20',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-21',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-22',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-23',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-24',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-25',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-26',
    week: 1,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-27',
    week: 2,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
  {
    date: '2022-02-28',
    week: 2,
    season: 'christmas',
    passages: [],
    holidays: [],
    notes: ['[HTML][HTML] '],
  },
];
