export const copy = {
  title: 'Liturgia Godzin',
  subtitle: 'Reformowany Kościół Katolicki w\u00A0Polsce',
  backToList: 'wróć do listy',
  firstWeekTitle: 'Tydzień pierwszy',
  secondWeekTitle: 'Tydzień drugi',
  logoAlt: 'logo Kościoła',
  chevronImageAlt: 'chevron',
  seeLessInfo: 'ukryj informacje',
  seeMoreInfo: 'więcej informacji',
  sundayReadings:
    'Dzisiejsze czytania znajdziesz również na [HTML]naszej stronie.[HTML]',
  appName: 'Oficjum',
  offlineHeader: 'Jesteś offline.',
  offlineDesc: 'Połącz się z siecią, aby pobrać tekst.',
  reloadPage: 'Spróbuj ponownie',
  updateAvailableHeader: 'Dostępna aktualizacja',
  updateAvailableDescription:
    'Uruchom ponownie aplikację, aby zobaczyć najnowszą wersję.',
  customPrayerHeadline: 'Modlitwy na święta',
  or: 'Albo:',
  linksTitle: '[HTML]Modlitwy na dziś: [HTML]',
  notToday:
    'Upsi! Ktoś zapomniał o kalendarzu na ten miesiąc 🙁. Jeżeli to pomoże - poniżej znajdują się teksty na okres w ciągu roku.',
  silence: 'Chwila ciszy...',
  readingsHeadline: 'Czytania liturgiczne',
  fastDay: 'DZIEŃ WSPÓLNEGO POSTU',
  settings: {
    headline: 'Ustawienia',
    goBackButton: 'wróć na stronę główną',
    resetSettings: 'Resetuj ustawienia',
    preview: `Tutaj możesz na bieżąco obserwować efekty wprowadzanych zmian. Dzięki temu masz pełną kontrolę nad wyglądem tekstu ✨`,
    fontSizeLabel: 'Rozmiar fontu',
    fontLabel: 'Font',
    theme: 'Motyw',
    switchToLight: 'Przełącz na tryb dzienny',
    switchToDark: 'Przełącz na tryb nocny',
    optionalContentLabel: 'Opcjonalne treści',
    displayIntercessions: 'Intencje modlitewne',
    displayExaminationOfConscience: 'Rachunek sumienia',
    preferencesSaved: ' Ustawienia zapisane',
    preferencesDefault: 'Przywrócono ustawienia domyślne',
    clearCache: 'Wyczyść cache',
    cacheCleared: 'Cache został wyczyszczony',
  },
};

export default copy;
